### ISSUE TITLE
Failed with 'Invalid URL'

### ISSUE THREAD

**Issue by thewilkybarkid** [superfly/flyctl-actions#25] opened 2022-06-15 14:41 UTC
Seems like it was a one-off as the next build passed, but I had a failure (https://github.com/PREreview/prereview.org/runs/6901353686) with the logs:

```
2022-06-15T14:03:24.6477304Z ##[group]Run superfly/flyctl-actions/setup-flyctl@master
2022-06-15T14:03:24.6477743Z with:
2022-06-15T14:03:24.6478014Z   version: latest
2022-06-15T14:03:24.6478308Z ##[endgroup]
2022-06-15T14:03:33.2538818Z Invalid URL
2022-06-15T14:03:33.2540421Z Waiting 17 seconds before trying again
2022-06-15T14:03:50.2697408Z Invalid URL
2022-06-15T14:03:50.2697950Z Waiting 19 seconds before trying again
2022-06-15T14:04:09.2923557Z ##[error]Invalid URL
```

I'm guessing it was unable to find the version number for some reason, but I've not been able to work out what caused 'Invalid URL'; could more logging be added to help debug issues?

**Comment by thewilkybarkid** [comment] 2022-08-08 14:32
Just saw it again (https://github.com/PREreview/prereview.org/runs/7727543949). Output seems the same, though the wait times are a little shorter:


```
2022-08-08T14:19:27.9261910Z ##[group]Run superfly/flyctl-actions/setup-flyctl@master
2022-08-08T14:19:27.9262348Z with:
2022-08-08T14:19:27.9262610Z   version: latest
2022-08-08T14:19:27.9262888Z ##[endgroup]
2022-08-08T14:19:28.7534902Z Invalid URL
2022-08-08T14:19:28.7536564Z Waiting 10 seconds before trying again
2022-08-08T14:19:38.7519362Z Invalid URL
2022-08-08T14:19:38.7520190Z Waiting 10 seconds before trying again
2022-08-08T14:19:48.7666966Z ##[error]Invalid URL
```

**Comment by khaiql** [comment] 2022-10-28 03:25
I've just got the same error too

**Comment by ivanvanderbyl** [comment] 2022-10-28 03:25
I was able to fix this by specifying the version to use:

```
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.422
```

**Comment by codewithcheese** [comment] 2023-09-04 07:46
@jsierles Bitten by this today. Action was working an hour ago but now getting, added `with: version: 0.1.87` since it was reported in the previous successful run but still failed.

```
 ##[debug]Evaluating condition for step: 'Setup flyctl'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Setup flyctl
##[debug]Loading inputs
##[debug]Loading env
Run superfly/flyctl-actions/setup-flyctl@master
  with:
    version: 0.1.87
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
##[debug]isExplicit: 0.1.87
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/flyctl/0.1.87/x64
##[debug]not found
##[debug]Downloading 
##[debug]Destination /home/runner/work/_temp/581538ce-f9be-4e1e-b603-5ba37a21d9a4
Invalid URL
Waiting 16 seconds before trying again
Invalid URL
Waiting 11 seconds before trying again
Error: Invalid URL
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Setup flyctl
```

There was a PR that logged the download URL for this situation but seems to have been removed https://github.com/superfly/flyctl-actions/pull/22

**Comment by codewithcheese** [comment] 2023-09-04 07:50
Pinning one version earlier to `0.1.86` did not error

**Comment by jsierles** [comment] 2023-09-05 22:22
This is indirectly caused by Fly.io API failures. Closing again, but leaving this comment as a reminder.

**Closed by jsierles** 2023-09-05 22:22 UTC
